name: CI

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node: [12.x, 14.x, 15.x]
    name: test/node ${{matrix.node}}/${{matrix.platform}}
    runs-on: ${{matrix.platform}}
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-node@main
      with:
        node-version: ${{matrix.node}}
    - run: npm ci
    - run: npm test
  coverage:
    needs: [test]
    name: test/coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-node@main
      with:
        node-version: 15
    - run: npm ci
    - run: npm run coverage
    - name: Run codacy coverage reporter
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: ${{secrets.CODACY_PROJECT_TOKEN}}
        coverage-reports: coverage/lcov.info
